name: Manual Echo Workflow

on:
  workflow_dispatch:  # Permet d'exécuter le workflow manuellement depuis l'interface GitHub

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display message
        run: echo "Hello, this is a manually triggered echo from GitHub Actions!"
