name: Echo Secrets on PR Target

on:
  pull_request_target:
   

jobs:
  encode-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Encode secret in Base64
        run: echo -n "${{ secrets.MY_SECRET }}" | base64
