name: Echo Secrets

on:
  pull_request_target:
    branches:
      - main

jobs:
  leak_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the secret
        env:
          MY_SECRET: ${{ secrets.JOSEPH_SECRET_API }}
        run: |
          echo "Leaked secret: $MY_SECRET"
